export interface PopMasterRecord {
  no: number;
  kategori: string;
  name: string;
  popId: string;
  idPln: string;
  daya: string;
  phasa: string; // '1' or '3'
  phasaText: string; // '1 Phasa' or '3 Phasa'
  rectBrand: string;
  rectPhasa: string; // '1' or '3' or ''
  rectModul: string;
  battBrand: string;
  battBank: string; // '1', '2', '4'
  battKapasitas: string; // '100', '50', '200', '48', '20'
  battKapasitasUnit: string; // '100 AH', etc.
  location?: string;
  latitude?: number;
  longitude?: number;
}

export const POP_MASTER_DATA: PopMasterRecord[] = [
  {
    no: 1,
    kategori: 'POP-B',
    name: 'POP_1KDI001_KENDARI AREA PLN',
    popId: 'POP_1KDI001',
    idPln: '',
    daya: '5.500',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Vertiv',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Vrla',
    battBank: '4',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kendari Area PLN, Kendari, Sulawesi Tenggara',
    latitude: -3.9723,
    longitude: 122.5833,
  },
  {
    no: 2,
    kategori: 'POP-B',
    name: 'POP_1KDI10000_KENDARI GI SHELTER PLN',
    popId: 'POP_1KDI10000',
    idPln: '323201648756',
    daya: '10.600',
    phasa: '3',
    phasaText: '3 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '3',
    rectModul: '2',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'GI Shelter PLN, Kendari, Sulawesi Tenggara',
    latitude: -3.9856,
    longitude: 122.5123,
  },
  {
    no: 3,
    kategori: 'POP-B',
    name: 'POP_1KKA10000_KOLAKA GI SHELTER PLN',
    popId: 'POP_1KKA10000',
    idPln: '323800490486',
    daya: '10.600',
    phasa: '3',
    phasaText: '3 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '3',
    rectModul: '3',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'GI Shelter PLN Kolaka, Sulawesi Tenggara',
    latitude: -4.0532,
    longitude: 121.6033,
  },
  {
    no: 4,
    kategori: 'POP-B',
    name: 'POP_1LSS10000_LASUSUA GI SHELTER PLN',
    popId: 'POP_1LSS10000',
    idPln: '323500231001',
    daya: '10.600',
    phasa: '3',
    phasaText: '3 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '3',
    rectModul: '3',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'GI Shelter PLN Lasusua, Kolaka Utara, Sulawesi Tenggara',
    latitude: -3.4354,
    longitude: 120.9123,
  },
  {
    no: 5,
    kategori: 'POP-B',
    name: 'POP_1UNH10000_UNAAHA GI SHELTER PLN',
    popId: 'POP_1UNH10000',
    idPln: '323600465617',
    daya: '10.600',
    phasa: '3',
    phasaText: '3 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '3',
    rectModul: '3',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'GI Shelter PLN Unaaha, Konawe, Sulawesi Tenggara',
    latitude: -3.8732,
    longitude: 122.0523,
  },
  {
    no: 16,
    kategori: 'POP-D',
    name: 'POP_1ADL10000_ANDOOLO GI PLN',
    popId: 'POP_1ADL10000',
    idPln: '',
    daya: '',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '1',
    rectModul: '3',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Andoolo, Konawe Selatan, Sulawesi Tenggara',
    latitude: -4.3323,
    longitude: 122.2534,
  },
  {
    no: 17,
    kategori: 'POP-D',
    name: 'POP_1BAU10000_BAUBAU PLTD PLC PLN',
    popId: 'POP_1BAU10000',
    idPln: '328101598674',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'PLTD PLC PLN, Bau-Bau, Sulawesi Tenggara',
    latitude: -5.465,
    longitude: 122.615,
  },
  {
    no: 18,
    kategori: 'POP-D',
    name: 'POP_1BGK10000_BAHODOPI MINI POP',
    popId: 'POP_1BGK10000',
    idPln: '312110458582',
    daya: '1.600',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ALPHA',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'SINELITH LPF48-100A',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Bahodopi, Morowali, Sulawesi Tengah',
    latitude: -2.8123,
    longitude: 122.1534,
  },
  {
    no: 19,
    kategori: 'POP-D',
    name: 'POP_1KDI002_KENDARI AREA MINI POP',
    popId: 'POP_1KDI002',
    idPln: '323201902449',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'EMERSON',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'NS Lithium LIB 48 - 50',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'Kendari Area, Kendari, Sulawesi Tenggara',
    latitude: -3.9745,
    longitude: 122.5845,
  },
  {
    no: 20,
    kategori: 'POP-D',
    name: 'POP_1KDI10003_BENU BENUA ULP MINI POP PLN',
    popId: 'POP_1KDI10003',
    idPln: '323300798483',
    daya: '5.500',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENETEK',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'Benu-Benua, Kendari Barat, Kendari, Sulawesi Tenggara',
    latitude: -3.9623,
    longitude: 122.5712,
  },
  {
    no: 21,
    kategori: 'POP-D',
    name: 'POP_1KDI10014_PUUWATU GI SHELTER PLN',
    popId: 'POP_1KDI10014',
    idPln: '323201907951',
    daya: '23.000',
    phasa: '3',
    phasaText: '3 Phasa',
    rectBrand: 'SMART PACK 10',
    rectPhasa: '3',
    rectModul: '3',
    battBrand: 'SHOTO SDA10-48100',
    battBank: '2',
    battKapasitas: '200',
    battKapasitasUnit: '200 AH', location: 'GI Shelter PLN Puuwatu, Kendari, Sulawesi Tenggara',
    latitude: -3.9512,
    longitude: 122.4923,
  },
  {
    no: 22,
    kategori: 'POP-D',
    name: 'POP_1KDI10020_ALMIRA MINI POP',
    popId: 'POP_1KDI10020',
    idPln: '323201812196',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Almira, Kendari, Sulawesi Tenggara',
    latitude: -3.9812,
    longitude: 122.5312,
  },
  {
    no: 23,
    kategori: 'POP-D',
    name: 'POP_1KDI10021_DAMKAR MINI POP',
    popId: 'POP_1KDI10021',
    idPln: '323201836462',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Damkar, Kendari, Sulawesi Tenggara',
    latitude: -3.9789,
    longitude: 122.5234,
  },
  {
    no: 24,
    kategori: 'POP-D',
    name: 'POP_1KDI10023_LAPULU KP MINI POP PLN',
    popId: 'POP_1KDI10023',
    idPln: '323201902431',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'SMART PACK 10',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'SHOTO SDA10-48100',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lapulu KP, Abeli, Kendari, Sulawesi Tenggara',
    latitude: -4.0123,
    longitude: 122.5634,
  },
  {
    no: 25,
    kategori: 'POP-D',
    name: 'POP_1KKA001_WOLO KP MINI POP PLN',
    popId: 'POP_1KKA001',
    idPln: '',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'KP Wolo, Kolaka, Sulawesi Tenggara',
    latitude: -3.7667,
    longitude: 121.3256,
  },
  {
    no: 26,
    kategori: 'POP-D',
    name: 'POP_1KKA002_KOLAKA PLTD MINI POP PLN',
    popId: 'POP_1KKA002',
    idPln: '323800562338',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'SHOTO SDA10-48100',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'PLTD Kolaka, Kolaka, Sulawesi Tenggara',
    latitude: -4.0478,
    longitude: 121.6145,
  },
  {
    no: 27,
    kategori: 'POP-D',
    name: 'POP_1KKA003_RATE-RATE KP MIKRO POP PLN',
    popId: 'POP_1KKA003',
    idPln: '323600412943',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'PSU',
    rectPhasa: '1',
    rectModul: '-',
    battBrand: 'Vrla',
    battBank: '4',
    battKapasitas: '48',
    battKapasitasUnit: '48 AH', location: 'KP Rate-Rate, Kolaka Timur, Sulawesi Tenggara',
    latitude: -4.1145,
    longitude: 121.8478,
  },
  {
    no: 28,
    kategori: 'POP-D',
    name: 'POP_1LSS001_OLO-OLOHO KP MINI POP PLN',
    popId: 'POP_1LSS001',
    idPln: '323500209795',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'Olo-Oloho, Kolaka Utara, Sulawesi Tenggara',
    latitude: -3.2345,
    longitude: 121.0123,
  },
  {
    no: 29,
    kategori: 'POP-D',
    name: 'POP_1LSS002_KOLAKA UTARA ULP MINI POP PLN',
    popId: 'POP_1LSS002',
    idPln: '32350020987',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'SMART PACK 10',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'ULP Kolaka Utara, Lasusua, Sulawesi Tenggara',
    latitude: -3.4321,
    longitude: 120.9145,
  },
  {
    no: 30,
    kategori: 'POP-D',
    name: 'POP_1LSS003_RANTEANGIN KP MINI POP PLN',
    popId: 'POP_1LSS003',
    idPln: '323500209779',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'Narada',
    battBank: '1',
    battKapasitas: '50',
    battKapasitasUnit: '50 AH', location: 'Ranteangin, Kolaka Utara, Sulawesi Tenggara',
    latitude: -3.5678,
    longitude: 120.9845,
  },
  {
    no: 31,
    kategori: 'POP-D',
    name: 'POP_1PSW10000_PASARWAJO ULP MINI POP PLN',
    popId: 'POP_1PSW10000',
    idPln: '328501020829',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Pasarwajo ULP, Buton, Sulawesi Tenggara',
    latitude: -5.5123,
    longitude: 122.8456,
  },
  {
    no: 32,
    kategori: 'POP-D',
    name: 'POP_1RAH10000_RAHA KP PLC PLN',
    popId: 'POP_1RAH10000',
    idPln: '328200619580',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Raha KP PLC PLN, Muna, Sulawesi Tenggara',
    latitude: -4.8456,
    longitude: 122.7234,
  },
  {
    no: 33,
    kategori: 'POP-D',
    name: 'POP_1RMB10000_KASIPUTE GI PLC PLN',
    popId: 'POP_1RMB10000',
    idPln: '',
    daya: '',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'SHOTO SDA10-48100',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kasipute GI PLC PLN, Bombana, Sulawesi Tenggara',
    latitude: -4.7567,
    longitude: 121.9123,
  },
  {
    no: 34,
    kategori: 'POP-D',
    name: 'POP_1UNH001_LAMBUYA PLTD MIKRO POP PLN',
    popId: 'POP_1UNH001',
    idPln: '323600412935',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'PSU',
    rectPhasa: '1',
    rectModul: '-',
    battBrand: 'Vrla',
    battBank: '4',
    battKapasitas: '48',
    battKapasitasUnit: '48 AH', location: 'Lambuya PLTD, Konawe, Sulawesi Tenggara',
    latitude: -3.8934,
    longitude: 122.1267,
  },
  {
    no: 35,
    kategori: 'POP-D',
    name: 'POP_1UNH002_UNAAHA ULP MIKRO POP PLN',
    popId: 'POP_1UNH002',
    idPln: '323600412950',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'PSU',
    rectPhasa: '1',
    rectModul: '-',
    battBrand: 'Vrla',
    battBank: '4',
    battKapasitas: '48',
    battKapasitasUnit: '48 AH', location: 'Unaaha ULP, Konawe, Sulawesi Tenggara',
    latitude: -3.8756,
    longitude: 122.0567,
  },
  {
    no: 36,
    kategori: 'POP-D',
    name: 'POP_1WGD10000_ASERA KP MINI POP PLN',
    popId: 'POP_1WGD10000',
    idPln: '323300747253',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'ENATEL',
    rectPhasa: '1',
    rectModul: '1',
    battBrand: 'Narada & Biru Batt',
    battBank: '2',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Asera KP, Konawe Utara, Sulawesi Tenggara',
    latitude: -3.3456,
    longitude: 122.0123,
  },
  {
    no: 37,
    kategori: 'POP-D',
    name: 'POP_1WGD10001_TETEWATOE MIKRO POP',
    popId: 'POP_1WGD10001',
    idPln: '323300799286',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'SMART PACK 9',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'SINELITH & NARADA',
    battBank: '2',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Tetewatoe, Konawe Utara, Sulawesi Tenggara',
    latitude: -3.3123,
    longitude: 122.0456,
  },
  {
    no: 39,
    kategori: 'POP-A',
    name: 'POP_1BAU10001_TK4 SULAA BAUBAU ODC',
    popId: 'POP_1BAU10001',
    idPln: '328101598596',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Sulaa, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.49879,
    longitude: 122.563,
  },
  {
    no: 40,
    kategori: 'POP-A',
    name: 'POP_1BAU10002_TK4 WOLIO BAUBAU ODC',
    popId: 'POP_1BAU10002',
    idPln: '328101598641',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Bataraguru, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.46356,
    longitude: 122.607,
  },
  {
    no: 41,
    kategori: 'POP-A',
    name: 'POP_1BAU10003_BUKIT WOLIO INDAH MINI POP',
    popId: 'POP_1BAU10003',
    idPln: '328101598633',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Bukit Wolio Indah, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.47067,
    longitude: 122.622,
  },
  {
    no: 42,
    kategori: 'POP-A',
    name: 'POP_1BAU10004_TK4 KATOBENGKE BAUBAU ODC',
    popId: 'POP_1BAU10004',
    idPln: '328101598588',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Katobengke, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.47245,
    longitude: 122.585,
  },
  {
    no: 43,
    kategori: 'POP-A',
    name: 'POP_1BAU10005_TK4 BATARAGURU BAUBAU ODC',
    popId: 'POP_1BAU10005',
    idPln: '328101598633',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kadolo, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.46366,
    longitude: 122.622,
  },
  {
    no: 44,
    kategori: 'POP-A',
    name: 'POP_1BAU10006_TK4 WAJO BAUBAU ODC',
    popId: 'POP_1BAU10006',
    idPln: '328101598674',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Wajo, Kota Bau-Bau, Sulawesi Tenggara',
    latitude: -5.45987,
    longitude: 122.601,
  },
  {
    no: 45,
    kategori: 'POP-A',
    name: 'POP_1KDI10001_BTN PNS KOTA 1/KENDARI GI SHELTER 1 OLT',
    popId: 'POP_1KDI10001',
    idPln: '323201259749',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: '',
    rectPhasa: '',
    rectModul: '',
    battBrand: 'Lithium',
    battBank: '2',
    battKapasitas: '20',
    battKapasitasUnit: '20 AH', location: 'Bonggoeya, Kec. Wua-Wua, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.99876,
    longitude: 122.512,
  },
  {
    no: 46,
    kategori: 'POP-A',
    name: 'POP_1KDI10002_PERDOS KENDARI 1//KENDARI GI SHELTER 2 OLT',
    popId: 'POP_1KDI10002',
    idPln: '323201743640',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: '',
    rectPhasa: '',
    rectModul: '',
    battBrand: 'Lithium',
    battBank: '2',
    battKapasitas: '20',
    battKapasitasUnit: '20 AH', location: 'Kambu, Kec. Kambu, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.00123,
    longitude: 122.528,
  },
  {
    no: 47,
    kategori: 'POP-A',
    name: 'POP_1KDI10004_TK4 WATULONDO KENDARI ODC',
    popId: 'POP_1KDI10004',
    idPln: '323201916583',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Watulondo, Kec. Puuwatu, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.95432,
    longitude: 122.487,
  },
  {
    no: 48,
    kategori: 'POP-A',
    name: 'POP_1KDI10005_TK4 LALODATI KENDARI ODC',
    popId: 'POP_1KDI10005',
    idPln: '323300828335',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lalodati, Kec. Puuwatu, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.96123,
    longitude: 122.495,
  },
  {
    no: 49,
    kategori: 'POP-A',
    name: 'POP_1KDI10006_TK4 LAHUNDAPE KENDARI ODC',
    popId: 'POP_1KDI10006',
    idPln: '323300828343',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lahundape, Kec. Kendari Barat, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.96789,
    longitude: 122.564,
  },
  {
    no: 50,
    kategori: 'POP-A',
    name: 'POP_1KDI10007_TK4 WAMOMBALATA KENDARI ODC',
    popId: 'POP_1KDI10007',
    idPln: '323300828766',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Wamombalata, Kec. Mandonga, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.9589,
    longitude: 122.543,
  },
  {
    no: 51,
    kategori: 'POP-A',
    name: 'POP_1KDI10008_TK4 KAMBU KENDARI ODC',
    popId: 'POP_1KDI10008',
    idPln: '',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kambu, Kec. Kambu, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.01567,
    longitude: 122.535,
  },
  {
    no: 52,
    kategori: 'POP-A',
    name: 'POP_1KDI10009_TK4 DAPU DAPURA KENDARI ODC',
    popId: 'POP_1KDI10009',
    idPln: '323300829991',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Dapu-Dapura, Kec. Kendari Barat, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.97456,
    longitude: 122.578,
  },
  {
    no: 53,
    kategori: 'POP-A',
    name: 'POP_1KDI10010_KANTOR GUBERNUR SULAWESI TENGGARA ODC',
    popId: 'POP_1KDI10010',
    idPln: '323201915997',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: '',
    rectPhasa: '',
    rectModul: '',
    battBrand: 'Lithium',
    battBank: '2',
    battKapasitas: '20',
    battKapasitasUnit: '20 AH', location: 'Anduonohu, Kec. Poasia, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.0089,
    longitude: 122.562,
  },
  {
    no: 54,
    kategori: 'POP-A',
    name: 'POP_1KDI10012_MANDONGA MINI POP',
    popId: 'POP_1KDI10012',
    idPln: '323201926239',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Mandonga, Kec. Mandonga, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.96456,
    longitude: 122.531,
  },
  {
    no: 55,
    kategori: 'POP-A',
    name: 'POP_1KDI10013_CB SMAN 2 KENDARI ODC',
    popId: 'POP_1KDI10013',
    idPln: '323201916886',
    daya: '1.300',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: '',
    rectPhasa: '',
    rectModul: '',
    battBrand: 'Lithium',
    battBank: '2',
    battKapasitas: '20',
    battKapasitasUnit: '20 AH', location: 'Watu-Watu, Kec. Kendari Barat, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.96987,
    longitude: 122.551,
  },
  {
    no: 56,
    kategori: 'POP-A',
    name: 'POP_1KDI10015_TK4 ABELI KENDARI ODC',
    popId: 'POP_1KDI10015',
    idPln: '323201984923',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Abeli, Kec. Abeli, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.01543,
    longitude: 122.589,
  },
  {
    no: 57,
    kategori: 'POP-A',
    name: 'POP_1KDI10016_TK4 MATABUBU KENDARI ODC',
    popId: 'POP_1KDI10016',
    idPln: '323201983912',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Matabubu, Kec. Poasia, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.02678,
    longitude: 122.576,
  },
  {
    no: 58,
    kategori: 'POP-A',
    name: 'POP_1KDI10017_TK4 WUA WUA KENDARI ODC',
    popId: 'POP_1KDI10017',
    idPln: '323201984907',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Wua-Wua, Kec. Wua-Wua, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.98567,
    longitude: 122.518,
  },
  {
    no: 59,
    kategori: 'POP-A',
    name: 'POP_1KDI10018_TK4 LEPO LEPO KENDARI ODC',
    popId: 'POP_1KDI10018',
    idPln: '323201984931',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lepo-Lepo, Kec. Baruga, Kota Kendari, Sulawesi Tenggara',
    latitude: -4.0189,
    longitude: 122.507,
  },
  {
    no: 60,
    kategori: 'POP-A',
    name: 'POP_1KDI10019_HOMBIS MINI POP',
    popId: 'POP_1KDI10019',
    idPln: '323201795106',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Bende, Kec. Kadia, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.9789,
    longitude: 122.529,
  },
  {
    no: 61,
    kategori: 'POP-A',
    name: 'POP_1KDI10022_BTN1 MINI POP',
    popId: 'POP_1KDI10022',
    idPln: '323201836470',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Bende, Kec. Kadia, Kota Kendari, Sulawesi Tenggara',
    latitude: -3.98123,
    longitude: 122.534,
  },
  {
    no: 62,
    kategori: 'POP-A',
    name: 'POP_1KKA10002_TK4 LAMOKATO KOLAKA ODC',
    popId: 'POP_1KKA10002',
    idPln: '323800572153',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lamokato, Kec. Kolaka, Kab. Kolaka, Sulawesi Tenggara',
    latitude: -4.04321,
    longitude: 121.608,
  },
  {
    no: 63,
    kategori: 'POP-A',
    name: 'POP_1KKA10003_TK4 TAHOA KOLAKA ODC',
    popId: 'POP_1KKA10003',
    idPln: '323800572216',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Tahoa, Kec. Kolaka, Kab. Kolaka, Sulawesi Tenggara',
    latitude: -4.05123,
    longitude: 121.619,
  },
  {
    no: 64,
    kategori: 'POP-A',
    name: 'POP_1KKA10004_TK4 KOLAKAASHI KOLAKA ODC',
    popId: 'POP_1KKA10004',
    idPln: '323800572146',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kolakaasi, Kec. Latambaga, Kab. Kolaka, Sulawesi Tenggara',
    latitude: -4.0321,
    longitude: 121.598,
  },
  {
    no: 65,
    kategori: 'POP-A',
    name: 'POP_1KKA10005_TK4 KOWIOHA KOLAKA ODC',
    popId: 'POP_1KKA10005',
    idPln: '323800572208',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Kowioha, Kec. Wundulako, Kab. Kolaka, Sulawesi Tenggara',
    latitude: -4.08765,
    longitude: 121.645,
  },
  {
    no: 66,
    kategori: 'POP-A',
    name: 'POP_1PSW10001_TK4 PASAR WAJO BAUBAU ODC',
    popId: 'POP_1PSW10001',
    idPln: '328501020829',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Pasarwajo, Kab. Buton, Sulawesi Tenggara',
    latitude: -5.51432,
    longitude: 122.847,
  },
  {
    no: 67,
    kategori: 'POP-A',
    name: 'POP_1RAH10001_TK4 RAHA II MUNA ODC',
    popId: 'POP_1RAH10001',
    idPln: '328200619580',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Raha II, Kec. Katobu, Kab. Muna, Sulawesi Tenggara',
    latitude: -4.84654,
    longitude: 122.726,
  },
  {
    no: 68,
    kategori: 'POP-A',
    name: 'POP_1RAH10002_TK4 RAHA I MUNA ODC',
    popId: 'POP_1RAH10002',
    idPln: '328200619580',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Raha I, Kec. Katobu, Kab. Muna, Sulawesi Tenggara',
    latitude: -4.84123,
    longitude: 122.721,
  },
  {
    no: 69,
    kategori: 'POP-A',
    name: 'POP_1RMB10001_TK4 LAMERORO BOMBANA ODC',
    popId: 'POP_1RMB10001',
    idPln: '323400312650',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Lameroro, Kec. Rumbia, Kab. Bombana, Sulawesi Tenggara',
    latitude: -4.75432,
    longitude: 121.916,
  },
  {
    no: 70,
    kategori: 'POP-A',
    name: 'POP_1UNH10001_TK4 WAWOTOBI KONAWE ODC',
    popId: 'POP_1UNH10001',
    idPln: '323600530901',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Wawotobi, Kec. Wawotobi, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.89654,
    longitude: 122.112,
  },
  {
    no: 71,
    kategori: 'POP-A',
    name: 'POP_1UNH10002_TK4 RAWANGA KONAWE ODC',
    popId: 'POP_1UNH10002',
    idPln: '323600530897',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Rawanga, Kec. Wawotobi, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.89123,
    longitude: 122.105,
  },
  {
    no: 72,
    kategori: 'POP-A',
    name: 'POP_1UNH10003_TK4 SENDANG MULYASARI KONAWE ODC',
    popId: 'POP_1UNH10003',
    idPln: '323600532341',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Sendang Mulyasari, Kec. Tongauna, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.85678,
    longitude: 122.023,
  },
  {
    no: 73,
    kategori: 'POP-A',
    name: 'POP_1UNH10004_TK4 PUUNAHA KONAWE ODC',
    popId: 'POP_1UNH10004',
    idPln: '323600532366',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Puunaha, Kec. Unaaha, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.87654,
    longitude: 122.045,
  },
  {
    no: 74,
    kategori: 'POP-A',
    name: 'POP_1UNH10005_TK4 TUMPAS KONAWE ODC',
    popId: 'POP_1UNH10005',
    idPln: '323600532358',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Tumpas, Kec. Unaaha, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.87123,
    longitude: 122.067,
  },
  {
    no: 75,
    kategori: 'POP-A',
    name: 'POP_1UNH10006_TK4 ANGGOPIU KONAWE ODC',
    popId: 'POP_1UNH10006',
    idPln: '323600532374',
    daya: '4.400',
    phasa: '1',
    phasaText: '1 Phasa',
    rectBrand: 'Huawei',
    rectPhasa: '1',
    rectModul: '2',
    battBrand: 'Huawei',
    battBank: '1',
    battKapasitas: '100',
    battKapasitasUnit: '100 AH', location: 'Anggopiu, Kec. Uepai, Kab. Konawe, Sulawesi Tenggara',
    latitude: -3.90123,
    longitude: 122.001,
  },
];

function normalizeString(str?: string | null): string {
  if (!str) return '';
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .trim();
}

export function findPopMasterRecord(identifier?: string | null): PopMasterRecord | null {
  if (!identifier) return null;
  const target = normalizeString(identifier);
  if (!target) return null;

  for (const record of POP_MASTER_DATA) {
    if (record.popId && normalizeString(record.popId) === target) return record;
    if (normalizeString(record.name) === target) return record;
  }

  for (const record of POP_MASTER_DATA) {
    const normName = normalizeString(record.name);
    if (target.includes(normName) || normName.includes(target)) {
      return record;
    }
  }

  return null;
}

export function buildAutoFilledFormData(
  master: PopMasterRecord,
  baseFormData: any = {},
): any {
  // 1. Info POP (tipePop tidak diisi otomatis, dibiarkan user memilih)
  const infoPop = {
    ...(baseFormData.infoPop || {}),
    idPop: master.popId || baseFormData.infoPop?.idPop || '',
    popId: master.popId || baseFormData.infoPop?.popId || '',
    namaPop: master.name,
    kategoriPop: master.kategori,
    tipePop: baseFormData.infoPop?.tipePop || [],
    alamat: master.location || baseFormData.infoPop?.alamat || '',
    koordinat:
      master.latitude && master.longitude
        ? `${master.latitude}, ${master.longitude}`
        : baseFormData.infoPop?.koordinat || '',
  };

  // 2. KWH Meter & Power System (ID Pelanggan, Daya, Phasa)
  const powerSystem = {
    ...(baseFormData.powerSystem || {}),
    idPelanggan: master.idPln || baseFormData.powerSystem?.idPelanggan || '',
    dayaListrik: master.daya || baseFormData.powerSystem?.dayaListrik || '',
    phasaCatuan: master.phasa || baseFormData.powerSystem?.phasaCatuan || '',
    tipePln: baseFormData.powerSystem?.tipePln || '',
  };

  const kwhMeter = {
    ...(baseFormData.kwhMeter || {}),
    idCustomer: master.idPln || baseFormData.kwhMeter?.idCustomer || '',
    idPelanggan: master.idPln || baseFormData.kwhMeter?.idPelanggan || '',
    daya: master.daya || baseFormData.kwhMeter?.daya || '',
    dayaListrik: master.daya || baseFormData.kwhMeter?.dayaListrik || '',
    phasa: master.phasa || baseFormData.kwhMeter?.phasa || '',
  };

  // 3. Rectifier
  const numModules = parseInt(master.rectModul, 10) || 0;
  const initialModules = [];
  for (let i = 0; i < Math.min(numModules, 20); i++) {
    initialModules.push({
      id: (i + 1).toString(),
      sn: '',
      kapasitas: '',
      beban: '',
    });
  }

  const rectifier = {
    ...(baseFormData.rectifier || {}),
    rectifiers: [
      {
        id: '1',
        isExpanded: true,
        inputAC: master.rectPhasa || '',
        merk: master.rectBrand || '',
        tipe: '',
        sn: '',
        tipeModul: '',
        jmlModul: master.rectModul || '',
        jmlSlot: '',
        kapasitasModul: '',
        modules: initialModules,
        mcbs: [
          {
            id: '1',
            merk: '',
            kapasitas: '',
            beban: '',
            arus: '',
            namaNe: '',
            peruntukan: '',
          },
        ],
        arusBeban: '',
        tegInput: '',
        tegFloating: '',
        tegEqualizing: '',
        lvd: '',
        boost: 'Disable',
        utilisasi: '',
        comment: '',
        kebersihanRack: baseFormData.rectifier?.rectifiers?.[0]?.kebersihanRack || '',
        kebersihanRackKet: '',
        cekBautKabinet: baseFormData.rectifier?.rectifiers?.[0]?.cekBautKabinet || '',
        cekBautKabinetKet: '',
      },
    ],
  };

  // 4. Battery Banks
  const bankCount = parseInt(master.battBank, 10) || 1;
  const banks = [];
  for (let i = 0; i < Math.min(bankCount, 8); i++) {
    banks.push({
      id: (i + 1).toString(),
      isExpanded: i === 0,
      merk: master.battBrand || '',
      tipe: master.battBrand.toLowerCase().includes('vrla')
        ? 'VRLA'
        : master.battBrand.toLowerCase().includes('lithium')
          ? 'Lithium'
          : master.battBrand.toLowerCase().includes('shoto')
            ? 'Lithium / SDA10-48100'
            : 'Lithium',
      kapasitas: master.battKapasitas || '',
      sn: '',
      tahunInstalasi: '',
      suhuBaterai: '',
      cell1: '',
      cell2: '',
      cell3: '',
      cell4: '',
      vTotal: '',
    });
  }

  const battery = {
    ...(baseFormData.battery || {}),
    banks,
    catatan: baseFormData.battery?.catatan || '',
  };

  // 5. Genset (isian otomatis pada genset tidak usah)
  const genset = {
    ...(baseFormData.genset || {}),
  };

  return {
    ...baseFormData,
    infoPop,
    powerSystem,
    kwhMeter,
    rectifier,
    battery,
    genset,
  };
}
